// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkFJ63iaBffZ4qjdbzZ8riwoUOwVxMxPw',
    appId: '1:237907804029:web:9ce6df2af67d9c144cd614',
    messagingSenderId: '237907804029',
    projectId: 'social-dex-6c9e8',
    authDomain: 'social-dex-6c9e8.firebaseapp.com',
    storageBucket: 'social-dex-6c9e8.appspot.com',
    measurementId: 'G-Y7HFLZZLXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO8iqotjk9MoIHpulsPGM6eNNQ9oEZl7Y',
    appId: '1:237907804029:android:5d1af39c996abf854cd614',
    messagingSenderId: '237907804029',
    projectId: 'social-dex-6c9e8',
    storageBucket: 'social-dex-6c9e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLaKO_eUaTfCWbLKXCmbfJP5Zof1nE6wo',
    appId: '1:237907804029:ios:087b606a6d86849c4cd614',
    messagingSenderId: '237907804029',
    projectId: 'social-dex-6c9e8',
    storageBucket: 'social-dex-6c9e8.appspot.com',
    iosClientId: '237907804029-hav4ekfmsev2vpfk440r1k171t6c3gcp.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialDex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLaKO_eUaTfCWbLKXCmbfJP5Zof1nE6wo',
    appId: '1:237907804029:ios:e2d63b437451dfde4cd614',
    messagingSenderId: '237907804029',
    projectId: 'social-dex-6c9e8',
    storageBucket: 'social-dex-6c9e8.appspot.com',
    iosClientId: '237907804029-dfl8frc1mif5oamo96b5ec7cre9o4ral.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialDex.RunnerTests',
  );
}
